name: Next.js Docker Build and Push to TdA

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        uses: docker/build-push-action@v3
        with:
          context: ./
          tags: tda-nextjs:latest
          outputs: type=docker,dest=/tmp/tda-nextjs.tar

      - name: Upload to TdA
        uses: Tour-de-App/upload-app@tda-24
        with:
          team_secret: ${{ secrets.TEAM_SECRET }}
          image_name: tda-nextjs
          image_path: /tmp/tda-nextjs.tar
